---
# General cluster settings
external_interface: eth0
external_ip_address: DHCP
external_network_gateway: "{{ ansible_facts[external_interface].ipv4.address }}"
management_interface: eth1
management_ip_address: 10.142.255.254
management_network_baseaddress: 10.142.0.0
external_name_servers: [10.2.200.200]
install_medium: network
install_medium_network_packages:
  - "http://example.com/cm-config-cm.all.rpm"
  - "http://example.com/cm-config-yum.all.rpm"
timezone: Europe/Amsterdam
license:
  country: NL
  state: Amsterdam
  locality: Amsterdam
  organization: Bright Computing
  organizational_unit: Engineering 
  cluster_name: BrightCluster
  mac: "{{ ansible_default_ipv4.macaddress }}"
# AWS Settings
cloud: aws
aws_cloud_provider_default_director_type: t2.medium
aws_cloud_provider_default_region: eu-west-1
aws_cloud_provider_default_type: t3.medium
aws_cloud_provider_image_owners: 137677339600
aws_cloud_provider_ec2vpc_name: vpc-0
aws_cloud_provider_ec2vpc_region: eu-west-1
## The following are calculated in resolve_aws_params.yml
aws_cloud_provider_ec2vpc_vpc_id:
aws_public_network_cloud_subnet_id:
aws_private_network_cloud_subnet_id:
aws_cloud_provider_ec2vpc_security_group_node:
aws_cloud_provider_ec2vpc_security_group_director: