---
# Cluster credentials
product_key: ! vault <encrypted string>
db_cmd_password: ! vault <encrypted string>
ldap_root_pass: ! vault <encrypted string>
ldap_readonly_pass: ! vault <encrypted string>
slurm_user_pass: ! vault <encrypted string>
mysql_login_user: ! vault <encrypted string>
mysql_login_password: ! vault <encrypted string>
# AWS credentials
aws_cloud_provider_username: ! vault <encrypted string>
aws_cloud_provider_account_id: ! vault <encrypted string>
aws_cloud_provider_access_key_id: ! vault <encrypted string>
aws_cloud_provider_access_key_secret: ! vault <encrypted string>