---
- name: Install Bright head node on Azure
  hosts: head_node
  gather_facts: true
  become: true
  vars_files:
    - vars/stack.yml
    - vars/credentials.yml

  pre_tasks:
    - name: Resolve {{ cloud }} parameters
      include_tasks: "tasks/resolve_{{ cloud }}_params.yml"
      tags:
        - always

  roles:
    - role: brightcomputing.installer92.head_node
