# prepare
needed_packages:
  - rng-tools
  - mariadb-server
  - python3-pip
  - python3-setuptools
  - python3-PyMySQL
  - python3-dnf
  - gcc
  - automake
  - python3-devel
  - openldap-devel
  - less
  - vim
  - git
  - htop
  - langpacks-en
  - glibc-all-langpacks

needed_services:
  - mariadb
  - rngd

_mysql_root_password: _s3cret!db_root_password

mysql_user_home: /tmp
