---
# prepare variables, those are only used during the prepare.yml playbook
_grub_default_path: /etc/default/grub.d/50-cloudimg-settings.cfg
_cloud_type:   '"azure"'
_virt_type:    '"hyperv"'

# General cluster settings, (brightcomputing.installer variables)
external_interface: eth1
external_ip_address: DHCP
external_network_gateway: "{{ ansible_facts[external_interface].ipv4.address }}"
management_interface: eth0
management_ip_address: 10.142.255.254
management_network_baseaddress: 10.142.0.0
external_name_servers: [10.2.200.200]
install_medium: network
install_medium_network_packages:
  - "{{ ansible_env.HOME }}/cm-config-cm.all.deb"
  - "{{ ansible_env.HOME }}/cm-config-apt.all.deb"
post_install_default_image_archive: "{{ ansible_env.HOME }}/UBUNTU2204.tar.gz"
timezone: Europe/Amsterdam
license:
  country: NL
  state: Amsterdam
  locality: Amsterdam
  organization: Bright Computing
  organizational_unit: Engineering
  cluster_name: BrightCluster
  mac: "{{ ansible_default_ipv4.macaddress }}"
# Azure settings
cloud: azure

## The following are calculated in resolve_azure_params.yml
azure_cloud_provider_resource_group:
azure_cloud_provider_storage_account_name:
azure_network_name:
azure_network_cloud_subnet_id:
