---
- name: Install Bright RHEL8.5 head node
  hosts: rhel8u5-head
  gather_facts: true
  become: true
  vars_files:
    - vars/cluster-settings.yml
  vars:
    post_install_default_image_archive: '{{ ansible_env.HOME }}/RHEL8u5.tar.gz'

  pre_tasks:
    - name: Resolve {{ cloud }} parameters
      include_tasks: "tasks/resolve_{{ cloud }}_params.yml"
      tags:
        - always

    - name: Upload base distributions archive and repo packages
      copy:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}"
      loop:
        - RHEL8u5.tar.gz
        - cm-config-cm.noarch.rpm
        - cm-config-yum.noarch.rpm
      tags:
        - always

  roles:
    - role: brightcomputing.installer92.head_node
      vars:
        install_medium: network
        install_medium_network_packages:
          - "{{ ansible_env.HOME }}/cm-config-cm.noarch.rpm"
          - "{{ ansible_env.HOME }}/cm-config-yum.noarch.rpm"
        post_install_default_image_archive: '{{ ansible_env.HOME }}/RHEL8u5.tar.gz'
        cm_create_image_extra_args: "--resolvconf /etc/resolv.conf --enableextrarepo public "
